Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#Adding a new friend to our notebook:
key_list = list(notebook.keys())
i = 0

#a loop over dictionary values
for entry in notebook.values(): 
    print("Please add a new", key_list[i])
    new_entry = input()
    entry.append(new_entry)
    i += 1
print(notebook)
------------------

----- stdout -----
Please add a new First name
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
Cell [0;32mIn[25], line 8[0m
[1;32m      6[0m [38;5;28;01mfor[39;00m entry [38;5;129;01min[39;00m notebook[38;5;241m.[39mvalues(): 
[1;32m      7[0m     [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mPlease add a new[39m[38;5;124m"[39m, key_list[i])
[0;32m----> 8[0m     new_entry [38;5;241m=[39m [38;5;28;43minput[39;49m[43m([49m[43m)[49m
[1;32m      9[0m     entry[38;5;241m.[39mappend(new_entry)
[1;32m     10[0m     i [38;5;241m+[39m[38;5;241m=[39m [38;5;241m1[39m

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/ipykernel/kernelbase.py:1250[0m, in [0;36mKernel.raw_input[0;34m(self, prompt)[0m
[1;32m   1248[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_allow_stdin:
[1;32m   1249[0m     msg [38;5;241m=[39m [38;5;124m"[39m[38;5;124mraw_input was called, but this frontend does not support input requests.[39m[38;5;124m"[39m
[0;32m-> 1250[0m     [38;5;28;01mraise[39;00m StdinNotImplementedError(msg)
[1;32m   1251[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_input_request(
[1;32m   1252[0m     [38;5;28mstr[39m(prompt),
[1;32m   1253[0m     [38;5;28mself[39m[38;5;241m.[39m_parent_ident[[38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m],
[1;32m   1254[0m     [38;5;28mself[39m[38;5;241m.[39mget_parent([38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m),
[1;32m   1255[0m     password[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m   1256[0m )

[0;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.

